baseurl: ""

title      : Bond Buddies - Experts in Bond Origination & Home Loans | Durban
email      : anandie@bondbuddies.co.za
description: Looking for expert assistance with your home loan? Contact Anandie vand der Westhuizen at Bond Buddies today. Our seasoned property professionals specialize in home loans and property finance, committed to excellence and building long-term relationships. Discover tailored solutions for bonds, home loans, and origination with our passionate team. Trust Bond Buddies for your home financing needs.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: xxx

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Homeloans

company: Bond Buddies

url: https://evohomeloans.co.za/bond-originator/bbb/

address: 000 Roadname, Suburb, City, Province, 0000